import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import ActiveStatus from './components/ActiveStatus';
import { Toaster } from './components/toast/Toaster';
import AuthContext from './context/authContext';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Messenger Clone',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AuthContext>
          {children}
          <Toaster />
          <ActiveStatus />
        </AuthContext>
      </body>
    </html>
  );
}
